// Copies the existing docs markdown (www/docs/content) into Starlight's content folder,
// converting it on the way. The source files are never modified: this is a trial of how
// the current content looks as a Starlight site.
//
// Conversions:
//   - the first "# Heading" becomes the page title in frontmatter
//   - the first paragraph becomes the page description (meta description)
//   - "?p=doc/layout/flank" links become "/docs/doc/layout/flank/"
//   - "::: sdk js ... :::" sections become Starlight <Tabs>, which makes the page .mdx;
//     headings inside them move two levels down to stay out of the page contents
//   - each XML block becomes tabs with the same snippet in every SDK, generated by the engine
//   - standalone "---" lines outside code are dropped, as the current renderer hides <hr>
//
// All tabs share one sync key, so a language picked in the header, in a code block or on the
// install page shows everywhere, and Starlight remembers it across pages.
//
// Usage: node scripts/sync-content.mjs            one sync
//        node scripts/sync-content.mjs --watch    sync, then resync on every change

import { promises as fs, watch } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import vm from 'node:vm';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');
const SRC = path.resolve(root, '../www/docs/content');
const EXTRA = path.resolve(root, 'extra');
const DEST = path.resolve(root, 'src/content/docs');
const CODEGEN = path.resolve(root, '../www/assets/js/lpdf-demo');
const BASE = '/docs';

// The sync key and labels are shared with src/components/code-lang-select.astro.
const SYNC_KEY = 'lang';
const SDK_LABELS = { js: 'Node.js', php: 'PHP', python: 'Python', dotnet: '.NET' };
const CODE_TABS = [
    { target: 'js', lang: 'js' },
    { target: 'php', lang: 'php' },
    { target: 'python', lang: 'python' },
    { target: 'dotnet', lang: 'csharp' },
];

let codegenLoad;

/**
 * Loads the engine's XML-to-code generator: the same WASM build the current docs run in the
 * browser, run here once per process so the pages ship the generated code as plain HTML.
 */
function loadCodegen()
{
    codegenLoad ??= (async () =>
    {
        const web = await import(pathToFileURL(path.join(CODEGEN, 'lpdf-web.js')).href);
        await web.default({ module_or_path: await fs.readFile(path.join(CODEGEN, 'lpdf_bg.wasm')) });
        return (xml, target) => web.codegen_fragment_wasm(xml, JSON.stringify({ target }));
    })();
    return codegenLoad;
}

async function walk(dir, rel = '')
{
    const out = [];
    let entries = [];
    try { entries = await fs.readdir(path.join(dir, rel), { withFileTypes: true }); }
    catch { return out; }
    for (const e of entries)
    {
        const r = rel ? `${rel}/${e.name}` : e.name;
        if (e.isDirectory()) out.push(...await walk(dir, r));
        else if (/\.mdx?$/.test(e.name)) out.push(r);
    }
    return out;
}

/** Plain text of the first prose paragraph, for the meta description. */
function firstParagraph(body)
{
    let inFence = false;
    const para = [];
    for (const line of body.split('\n'))
    {
        if (/^```/.test(line)) { inFence = !inFence; if (para.length) break; continue; }
        if (inFence) continue;
        const t = line.trim();
        if (!t) { if (para.length) break; continue; }
        if (/^(#|\||[-*+] |\d+\. |:::|<|>|import )/.test(t)) { if (para.length) break; continue; }
        para.push(t);
    }
    let text = para.join(' ')
        .replace(/\[([^\]]+)\]\([^)]*\)/g, '$1')
        .replace(/`([^`]*)`/g, '$1')
        .replace(/(\*\*|__|\*|_)(\S[^*_]*?)\1/g, '$2')
        .replace(/\s+/g, ' ')
        .trim();
    if (text.length > 160)
    {
        text = text.slice(0, 157);
        text = text.slice(0, text.lastIndexOf(' ')) + '…';
    }
    return text;
}

/**
 * Moves "##" and "###" headings two levels down. The table of contents lists levels 2 and 3,
 * so headings inside tabs would otherwise appear once per tab (Requirements four times).
 */
function demoteHeadings(md)
{
    let inFence = false;
    return md.split('\n').map(line =>
    {
        if (/^```/.test(line)) inFence = !inFence;
        return !inFence && /^#{2,3} /.test(line) ? `##${line}` : line;
    }).join('\n');
}

function sdkToTabs(body)
{
    return body.replace(/(?:^::: sdk \w+\n[\s\S]*?^:::[ \t]*$\n*)+/gm, run =>
    {
        const items = [...run.matchAll(/^::: sdk (\w+)\n([\s\S]*?)^:::[ \t]*$/gm)]
            .map(([, sdk, inner]) =>
                `<TabItem label="${SDK_LABELS[sdk] ?? sdk}">\n\n${demoteHeadings(inner.trim())}\n\n</TabItem>`);
        return `<Tabs syncKey="${SYNC_KEY}">\n\n${items.join('\n\n')}\n\n</Tabs>\n\n`;
    });
}

/**
 * The same XML snippet in every SDK, or the reason it stays XML only. The generator falls back
 * to L.element for elements it does not know (full documents, assets) and leaves TODO comments
 * for features it cannot express (data binding); text that runs over several lines comes out
 * as a broken string, which the JavaScript parse catches.
 */
function generateCode(xml, codegen)
{
    const variants = [];
    for (const { target, lang } of CODE_TABS)
    {
        let code;
        try { code = codegen(xml, target).trimEnd(); }
        catch (err) { return { reason: `generator error: ${err}` }; }
        if (code.includes('L.element(') || code.includes('L::element(') || code.includes('L.Element(')) return { reason: 'unknown element' };
        if (code.includes('TODO')) return { reason: 'unsupported feature' };
        variants.push({ label: SDK_LABELS[target], lang, code });
    }
    // Compiles only, never runs: the code is the generator's own output.
    try { new vm.Script(variants[0].code); }
    catch { return { reason: 'invalid code' }; }
    return { variants };
}

/**
 * Turns each XML block into tabs: XML first, then the generated SDK code. Blocks inside
 * "::: sdk" sections are SDK configuration (a .csproj, say) and stay as written, as does any
 * block the generator cannot express.
 */
function xmlToCodeTabs(body, rel, codegen, xmlOnly)
{
    const lines = body.split('\n');
    const out = [];
    let inSdk = false;
    let block = 0;
    for (let i = 0; i < lines.length; i++)
    {
        const line = lines[i];
        if (/^::: sdk \w+\s*$/.test(line)) inSdk = true;
        else if (/^:::\s*$/.test(line)) inSdk = false;

        if (!/^```/.test(line)) { out.push(line); continue; }

        let end = i + 1;
        while (end < lines.length && !/^```\s*$/.test(lines[end])) end++;
        const fence = lines.slice(i, end + 1);
        i = end;

        if (!/^```xml\s*$/.test(line) || inSdk) { out.push(...fence); continue; }
        block++;
        const xml = fence.slice(1, -1).join('\n');
        const { variants, reason } = generateCode(xml, codegen);
        if (!variants)
        {
            xmlOnly.push(`${rel} block ${block}: ${reason}`);
            out.push(...fence);
            continue;
        }
        const items = [
            `<TabItem label="XML">\n\n${fence.join('\n')}\n\n</TabItem>`,
            ...variants.map(({ label, lang, code }) => `<TabItem label="${label}">\n\n\`\`\`${lang}\n${code}\n\`\`\`\n\n</TabItem>`),
        ];
        out.push(`<Tabs syncKey="${SYNC_KEY}">\n\n${items.join('\n\n')}\n\n</Tabs>`);
    }
    return out.join('\n');
}

function transform(rel, text, codegen, xmlOnly)
{
    const lines = text.replace(/\r\n/g, '\n').split('\n');

    let title = path.basename(rel).replace(/\.mdx?$/, '');
    const first = lines.findIndex(l => l.trim() !== '');
    if (first >= 0 && /^# /.test(lines[first]))
    {
        title = lines[first].slice(2).trim();
        lines.splice(first, 1);
    }

    let inFence = false;
    const kept = [];
    for (const line of lines)
    {
        if (/^```/.test(line)) inFence = !inFence;
        if (!inFence && /^---\s*$/.test(line)) continue;
        kept.push(line);
    }
    let body = kept.join('\n').replace(/^\n+/, '');

    body = body.replace(/\]\(\/?\?p=([^)#\s]+)(#[^)\s]*)?\)/g,
        (_, p, hash = '') => `](${BASE}/${p.replace(/\./g, '/')}/${hash})`);

    const description = firstParagraph(body);

    body = sdkToTabs(xmlToCodeTabs(body, rel, codegen, xmlOnly));

    let ext = '.md';
    if (body.includes('<Tabs '))
    {
        ext = '.mdx';
        body = `import { Tabs, TabItem } from '@astrojs/starlight/components';\n\n${body}`;
    }

    const fm = ['---', `title: ${JSON.stringify(title)}`];
    if (description) fm.push(`description: ${JSON.stringify(description)}`);
    fm.push('---', '', '');
    return { out: rel.replace(/\.mdx?$/, ext), content: fm.join('\n') + body };
}

export async function syncOnce()
{
    const outputs = new Map();
    const codegen = await loadCodegen();
    const xmlOnly = [];

    for (const rel of await walk(SRC))
    {
        const { out, content } = transform(rel, await fs.readFile(path.join(SRC, rel), 'utf8'), codegen, xmlOnly);
        outputs.set(out, content);
    }
    // Hand-written pages that exist only in the trial site, such as the landing page.
    for (const rel of await walk(EXTRA))
    {
        outputs.set(rel, await fs.readFile(path.join(EXTRA, rel), 'utf8'));
    }

    let written = 0;
    for (const [rel, content] of outputs)
    {
        const file = path.join(DEST, rel);
        let current = null;
        try { current = await fs.readFile(file, 'utf8'); } catch { /* new file */ }
        if (current === content) continue;
        await fs.mkdir(path.dirname(file), { recursive: true });
        await fs.writeFile(file, content, 'utf8');
        written++;
    }

    let removed = 0;
    for (const rel of await walk(DEST))
    {
        if (outputs.has(rel)) continue;
        await fs.rm(path.join(DEST, rel));
        removed++;
    }

    console.log(`[sync] ${outputs.size} pages, ${written} written, ${removed} removed`);
    if (xmlOnly.length) console.log(`[sync] ${xmlOnly.length} XML blocks without code tabs:\n  ${xmlOnly.join('\n  ')}`);
}

export function watchContent()
{
    let timer;
    const resync = () =>
    {
        clearTimeout(timer);
        timer = setTimeout(() => syncOnce().catch(err => console.error('[sync]', err)), 150);
    };
    for (const dir of [SRC, EXTRA]) watch(dir, { recursive: true }, resync);
    console.log(`[sync] watching ${path.relative(root, SRC)} and ${path.relative(root, EXTRA)}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href)
{
    await syncOnce();
    if (process.argv.includes('--watch')) watchContent();
}
